package main

import (
	"github.com/rebeljah/gosqueak/jwt"
	"github.com/rebeljah/gosqueak/jwt/rs256"
	"github.com/rebeljah/gosqueak/services/message/api"
	"github.com/rebeljah/gosqueak/services/message/database"
	"github.com/rebeljah/gosqueak/services/message/chat"
)

const (
	ApiAddr         = "127.0.0.1:8082"
	AuthServerUrl   = "http://127.0.0.1:8081"
	JwtKeyPublicUrl = AuthServerUrl + "/jwtkeypub"
	JwtActorName    = "MESSAGE_API"
)

func main() {
	db := database.Load(database.DbFileName)
	defer db.Close()

	// api handles async messages and provides JWT to access the live msg server
	// api endpoints receive a JWT generated by external auth, then api can then
	// independtly verify this JWT.
	aud := jwt.NewAudience(rs256.FetchRsaPublicKey(JwtKeyPublicUrl), JwtActorName)
	apiServ := api.NewServer(ApiAddr, db, aud, chat.NewRelay())

	apiServ.Run()
}
